import {StyleSheet} from 'react-native';
import { COLORS } from '../../res/Colors';

const optionsStyles = StyleSheet.create({
  quizContainer: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: COLORS.quizBackGroundColor,
    alignItems: 'center',
  },
  quizCardStyle: {
    flex: 1,
    flexDirection: 'column',
    width: '95%',
    margin: 20,
    alignContent: 'center',
    backgroundColor: COLORS.appBackgroundColor,
    borderRadius: 15,
  },
  headerTextStyle: {
    flex: 0.13,
    width: '100%',
    marginTop: 5,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 40,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    letterSpacing: 2,
    color: COLORS.headerColor,
    alignContent: 'center',
    justifyContent: 'center',
  },
  questionCountStyle: {
    flex: 0.08,
    width: '100%',
    marginTop: 8,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 18,
    letterSpacing: 2,
    color: COLORS.questionCountColor,
    alignContent: 'center',
    justifyContent: 'center',
  },
  questionTextStyle: {
    maxHeight: 130,
    fontSize: 20,
    textAlign: 'center',
    verticalAlign: 'middle',
    color: 'white',
    margin: 10,
    padding: 5,
    lineHeight: 28,
  },
  answerContainerStyle: {
    width: '100%',
    flex: 0.7,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent:'center',
    padding: 8,
  },
  optionStyle: {
    minWidth : '80%',
    maxWidth : '90%',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.2,
    borderRadius: 50,
    margin: 8,
  },
  answerTextStyle: {
    width : '100%',
    height: '95%',
    fontSize: 15,
    color: 'white',
    letterSpacing : 0.5,
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  navigationButtonContainer: {
    width: '90%',
    flex: 0.07,
    alignSelf: 'center',
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15
  },
  navigationButtonStyle: {
    width: '60%',
    height: 45,
    borderRadius: 25,
    backgroundColor: COLORS.navigationButtonColor,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationTextStyle: {
    color: 'black',
    letterSpacing: 2,
    textAlign: 'center',
  },
});

export default optionsStyles;
